---
title: Using a Microscope
---

## Correct use of a microscope

Bacteria are much smaller than anything else you will have looked at under a microscope; most bacterial cells are approximately 1-3 µm long. Optimal set up of the microscope is therefore essential.

::: {.callout-important title="Safety tip for working with microscopes"}
Please note that you should not wear gloves while working with a microscope: you do not want to inadvertently transfer staining reagents (or other chemicals) onto it. 
:::

You should begin by placing a slide onto the stage and aligning the lowest power objective (usually the 10X objective) over it.

1.	Raise the stage using the coarse focusing knob so that the slide is about 5 mm away from the objective.

2.	Bring the slide into focus as best you can, first using the coarse focusing knob and then the fine focusing knob. You will be slowly lowering the stage so as to increase the distance between the slide and objective.

3.	Once you have focussed as best you can using this objective, you should move on to the next highest power objective. 

::: {.callout-tip title="Finding the focal plane"}
Often the plane of focus is extremely narrow, so that small, faint objects like stained bacteria may be easily missed as the focus passes through the plane. 

Thus, a good technique is to constantly move the focus up and down while also slowly moving the slide up/down or left/right on the stage. In this way, objects that flash in and out of focus tend to be more easily noticed by the eye. 
:::

At any point while using the microscope, you may wish to:

* Adjust the “interocular separation” of the eyepieces so that they are comfortably aligned with your eyes.

* Adjust the lamp voltage at any time when using a microscope in order to get a comfortable level of light.

### Use of oil with the microscope: 

*	The 100x objective is designed to be used with oil (it will have “oil” explicitly written on it), whereas the other objectives are not. 

*	Never use oil with any objective other than the 100x. Once you have added oil to your sample, never return to using a smaller magnification objective!

*	Only a very small amount of oil is needed, only add a tiny drop. Don’t flood the slide! 

*	When you have found your focus and optimised set-up with the 40x objective, swing the objectives half-way between the 40x and 100x. DO NOT move the stage or change the focus as you do this! Then gently add a very small drop of oil onto the spot of light you can see in your sample. Gently swing the 100x objective into place. 

*	You will most likely have to adjust the focus a little, but only use the fine adjustment at this stage. Ask for help if you have trouble finding the focus. Under no circumstances go back to the 40x, as it does not tolerate getting in contact to the immersion oil.

*	Residual oil will cling to the 100X objective after use, so make sure you clean it off with a lens tissue (specifically designed for this purpose) before putting the objective away. DO NOT use any other tissue to clean the lens.
