---
title: "Aims and Overview"
---

## Aims 
To understand how to work with microorganisms, both safely and aseptically


## Learning Outcomes
At the end of this laboratory session, you should understand:

- How to correctly use basic lab equipment including Bunsen burners, spreaders, and inoculating loops

- How to isolate single colonies using the streak plate method and by plating serial dilutions


## Competencies 

{{< include ./_includes/lab1comp.qmd >}}

## Importance

This laboratory session introduces key skills required for working safely and aseptically with microorganisms, which are fundamental for working as a microbiologist and used more broadly across a range of other disciplines in the life sciences.


## Overview of Lab 1

In this lab session, you will be learning (or further developing your skills in) a number of key microbiology skills:

1. You will prepare a number of different bacterial cultures, using the streak plate and spread plate methods (Task 1A).

2. You will extract plasmid DNA from bacterial cultures and analyse it using agarose gel electrophoresis (Task 1B).


::: {.todo title="To prepare for Lab 1"}

Before attending the practical lab, you should ensure that you have read and understood:

* The introductory sections covering [Good Lab Practice](./0goodlab.qmd) and [Aseptic Technique](./0aseptic.qmd)

* The introductory sections covering the theory on [Axenic culture](./1intro1.qmd), [Serial Dilutions](./1intro2.qmd), and [Plasmid DNA](./1intro3.qmd)

* The [Protocols](./1protocols.qmd) we will be following in the lab

You also must ensure that you have read and signed the safety forms, or you will not be admitted to the lab.

:::