---
title: "Basic Microbiology Skills"
---

## Introduction: Microbiology Skills

In this lab session, you will be learning (or further developing your skills in) a number of key microbiology skills:

1. You will prepare a number of different bacterial cultures, using the streak plate and spread plate methods (Task 1A).

2. You will extract plasmid DNA from bacterial cultures and analyse it using agarose gel electrophoresis (Task 1B).

## Working with Microbes in Axenic (Pure) Culture

As microbiologists, we often work with microbes in axenic (pure) culture. Although microbes in nature almost always exist in complex, multi-species communities, it is generally easiest to work with, and identify, microbes when they are in axenic culture.

::: {.discussion title="Why work with microbes in pure culture?"}

:::

### Streaking and Plating for Single Colonies

### Quantifying the Number of Microbes in a Sample: Serial Dilutions

## Introduction: Pathogenicity Islands

There are many different factors that affect the virulence of a pathogen. Some of these are found on pathogenicity islands and can be transmitted horizontally from one bacterial species to another (thus increasing virulence in the recipient).

In this lab, you will be looking at pathogens of the urinary tract and determining whether they carry any plasmids, which might carry antibiotic resistance determinants or contribute to bacterial virulence (Task 5A). 

::: {.case-study title="Case Study 1"}

There has recently been a large number of urinary tract infections in a local care home. The microbiologists investigating these cases have identified the aetiological agent as uropathogenic E. coli (UPEC). However, they are not sure why these UPEC strains seem to be more virulent than usual.

You have been called in as a consultant on the case because the microbiologists were impressed by your hypothesis that these UPEC strains might be acquiring virulence plasmids via horizontal gene transfer. Your task is to determine whether the isolated pathogens carry any plasmids (Task 

:::
 
### Isolating and Analysing Plasmid DNA

