---
title: "Aims and Overview"
---

# Aims 

To understand how to examine microorganisms, both at the macroscopic (colony morphology), and the microscopic (including the use of appropriate staining techniques) scale.


# Learning Outcomes

At the end of this laboratory session, you should understand:

*	How to identify microorganisms from their macroscopic characteristics.

*	How to identify microorganisms from their microscopic characteristics.

*	How to use differential media to identify bacterial species.


# Competencies 

{{< include ./_includes/lab2comp.qmd >}}

# Importance

This laboratory session aligns with lectures from BM329 block A and reinforces material relating to bacterial morphology, bacterial cell wall structure, bacterial identification and phylogeny, fungal classification.


## Overview of Lab 2

In this lab session, you will perform the following tasks:

* Task 2A: Observation of macroscopic characteristics

* Task 2B: Observation of microscopic characteristics

* Task 2C: Differential media - use of blood agar to differentiate bacteria based on their haemolytic activity


::: {.todo title="To prepare for Lab 2"}

Before attending the practical lab, you should ensure that you have read and understood:

* The introductory sections covering 

* The introductory sections covering the theory on 

* The [Protocols](./2protocols.qmd) we will be following in the lab

You also must ensure that you have read and signed the safety forms, or you will not be admitted to the lab.

:::

