# Microbial Identification {#sec-microbialID}

The techniques used to identify microbes can broadly be divided into molecular or culture based techniques. Molecular techniques rely on the identification of microbial macromolecules (usually DNA or proteins): examples include whole-genome sequencing, detection of specific sequences using polymerase chain reaction (PCR), and proteomic analysis using matrix-assisted laser desorption ionization-time of flight MS (MALDI-TOF MS). Culture-based techniques use differential stains, such as the Gram stain, selective and differential media, and biochemical tests to identify organisms based on their phenotypes. 

Most naturally occurring microorganisms exist in mixed populations, whether this is in a particular environment or in the context of a human host (e.g., when causing disease). Environmental and clinical samples must therefore be grown on solid media so that different microorganisms can form distinct colonies for isolation and identification.

Although microbiologists often work with pure cultures in the laboratory, and it can be simpler to study a single organism grown in pure culture, we are beginning to realise the importance of complex microbial communities and have begun to utilise co-cultures to study these communities in the lab. However, being able to work with pure cultures is an essential technique for any microbiologist, and is useful in many other disciplines as well (e.g., for any experimenter who wishes to clone or manipulate genes in their model organism; for the production and purification of proteins for structural or biochemical analysis; etc.)

The first step in identification of a pathogen is isolating that pathogen in pure culture. In clinical microbiology, we very often begin with a Gram stain (Figure 5) and use a dichotomous key (Figure 6) to identify organisms based on their phenotypes (e.g., ability to grow on particular media, phenotype(s) in certain biochemical test(s), etc.). The Gram stain allows us to characterize bacteria based on the structure of their cell walls, and moreover, observing the cells under the microscope and noting their shape and arrangement (Figure 7) can help to narrow down a preliminary identification. 


## Choice of media and growth conditions

Careful selection of growth media is necessary when working with microbes in the lab, as different microbes often require very different growth conditions. Researchers must provide microbes with supportive conditions for growth (Figure 8). All of the nutrients required for the cells to produce energy and the building blocks required for the synthesis of biological macromolecules and cell growth and division must be present (i.e., carbon, nitrogen, phosphorous, sulphur, etc.). In addition, researchers must take care to ensure that the physical environment supports the growth of the microbe they are trying to culture (e.g., pH, oxygen, temperature, etc.) Most of the human pathogens that you will encounter in this course grow well at 37˚C (human body temperature), and are able to grow well in the presence of oxygen. However, a number of clinically important microbes are anaerobic and grow only in anoxic conditions.


Microbial growth media can be categorized in different ways: based on their composition (rich/complex or defined media) or based on their function (selective or differential). Rich growth media provide all the essential nutrients required for the growth of a wide range of microorganisms. They contain complex ingredients like peptones, extracts, and sugars, which support the growth of various organisms without specific nutritional requirements. On the other hand, defined growth media have precisely known compositions, with each component specified in exact quantities. They are used to study the nutritional requirements of specific microorganisms, to control the growth conditions precisely, to study an organism’s metabolism, and in studies of auxotrophic mutants. 

Selective media are designed to encourage the growth of specific groups of microorganisms while inhibiting the growth of others. They contain substances such as antibiotics, dyes, or inhibitors that selectively suppress the growth of certain microorganisms, allowing the desired ones to grow. Differential media, on the other hand, contain indicators, such as dyes or pH indicators, that allow different microorganisms to be visually distinguished based on their metabolic activities. These media exploit the ability of certain bacteria to produce specific enzymes or metabolize specific substrates, leading to observable changes in the appearance of the medium. Some media, including the Mannitol Salt Agar (Figure 9) and MacConkey/lactose agar (Figure 10) that we will be using in this experiment, are both differential and selective.

We can take advantage of the inability of certain microbes to grow in specific conditions in our efforts to identify them (e.g., using their phenotypes in a dichotomous key). Clinical microbiologists have developed a number of different media that are useful for the identification of unknown microorganisms. Overall, the choice of growth media for a particular experiment will depend on the organism(s) being cultivated and the specific objectives of the experiment.


## Identification of microorganisms by microscopic characterisation

The individual cells of typical bacteria are very small. To be seen clearly, they must be fixed to a glass slide, stained, and then examined using a microscope fitted with an oil-immersion lens (x100) which is capable of producing an overall magnification of at least x1000. The most common staining technique employed in microbiology is the Gram stain since it allows visualisation of the test bacterium under a light microscope and it is a discriminatory stain (i.e. it contributes to the identification of a microorganism, particularly when the information provided is used in conjunction with the macroscopic characteristics). 


Moulds are multicellular fungi. They are much larger than yeasts and they do not require the use of an oil-immersion lens to be seen clearly. The characteristics of their mycelia may be seen using the microscope’s low power objective lens (x10); the characteristics of their hyphae, conidiophores and spores may be seen using the high power lens (x40). Although no stains are required to visualise the sample, simple stains such as iodine solution or lactophenol cotton blue reagent are sometimes applied to highlight cellular morphology more clearly.

### Identification of microbes using selective and differential media

Macroscopic observations of bacterial colony morphology can be useful in the identification of different species, as you saw in Task 2A. In addition to examining bacteria grown on nutrient agar, you will also find a wide range of differential and selective media used in clinical microbiology. These use the fact that different bacterial species have characteristic physiological and biochemical characteristics that can help to identify them. Selective media allow the growth of some bacteria, but not others. Differential media exploit specific chemical products of metabolism to produce visual indications of their production (e.g. by changes in colour of the colony or growth media), which can then be used to help identify the producing organism. Some media may be both selective and differential; and, in some cases, you may need to use multiple selective/differential media in combination to correctly identify an unknown organism.



::: {.callout-note icon=false title="Case Study 1"}

## CASE STUDY 1: Strep throat?

Patient history: young child with a sore throat, mild fever, swollen lymph nodes, no history of previous Strep throat.

The clinician suspects that the child may have a Group A Strep (Streptococcus pyogenes) infection. However, many sore throats are caused by viruses instead. Before starting the child on a course of antibiotics, the clinician takes a throat swab culture and sends it to the lab for analysis.

Gram staining and microscopic observation showed the presence of a Gram-positive coccus-shaped bacterium. Your task is to identify the bacterial species causing this infection (Task 2C).

Differential media - use of blood agar to differentiate bacteria based on their haemolytic activity

Blood agar plates are a differential medium used to detect haemolytic activity in different microorganisms. They are also useful for the clinical microbiologist, as this medium is enriched with mammalian blood and thus supports the growth of many nutritionally fastidious organisms. Several pathogenic bacteria can produce a haemolysin capable of lysing red blood cells, and thus a zone of lysed cells appears around these bacteria when they are grown on blood agar plates. This diagnostic test is particularly useful for the identification of Streptococcal sp.

There are three types of haemolysis as illustrated in Figure 2.4. Beta haemolysis is complete haemolysis: the blood cells are lysed and a clear zone forms around the colony. In alpha haemolysis (sometimes called incomplete haemolysis), the blood cells are not actually lysed; instead, the haemoglobin is reduced to methaemoglobin, causing a greenish or brownish discoloration. Gamma haemolysis is the lack of haemolysis, with no change to the surrounding medium after bacterial growth. Note that some bacteria may produce more than one more haemolysin, and also some haemolysins are oxygen-sensitive and only function in anaerobic conditions).

You will be given an unknown Streptococcus sp. to identify based on its haemolytic activity, as well as a set of controls (strains with known alpha, beta, and gamma haemolytic activities).

:::

