---
title: "API-20E Tests"
---

## Using an API-20E test for the identification of <i>Escherichia, Salmonella, and Shigella</i> sp. {#sec-API20E}

This diagnostic test uses 21 miniaturised biochemical tests and a database to identify an unknown microorganism that is suspected of being a member of the Enterobacteriaceae. Tests are grouped together in units of three and individual tests have a value of 1, 2 or 4 associated with them. By adding the values corresponding to positive reactions within each group, a 7-digit code (Analytical Profile Index) is generated that should reference a specific microorganism in the manufacturer’s database. The database also gives an indication of the confidence of the result.

Because of the long time between two laboratory sessions in this course (2 weeks), we are unable to perform the API-20E test (instead, this experiment has been performed for you and the results posted here).

Protocol 3.2: Setting up an API-20E strip test.

1.	Working in groups, place a small amount of water in the incubation tray (under the API strip itself) to provide humidity during incubation.

2.	Prepare a milky (visibly turbid) suspension of your organism in sterile water.

3.	Use a plastic sterile pipette to half-fill test wells of your API strip with the above suspension (Holding the strip at a slight angle as well as letting the end of the pipette touch the side of a well will make this easier. Make sure all air bubbles are eliminated).

4.	When there is a line under a well (ADH, LDC, ODC, H2S, URE), add sterile mineral oil to completely fill in the well.

5.	When there is a box under a well (CIT, VP and GEL), add some more bacterial suspension to completely fill in the well.

6.	Place the plastic lid back on and label the tray with your name, date and organism code.

7.	Incubate at 37°C for 24 hours.


Interpretation of API 20E
Protocol 5.3: Completing the API 20E strip assay.

1.	Add one drop of reagent TDA (10% ferric chloride) to the well labelled as TDA.

2.	Add one drop of reagent IND (Kovacs’ reagent) to the well labelled as IND.

3.	Add one drop of reagent VP1 (40% KOH), THEN add one drop of reagent VP2 (6% alpha-naphtol) to the well labelled as VP.

4.	Wait for 10 min to observe colour changes.

5.	Read the colour reactions obtained for each well, and record your results (as positive or negative) on the provided slip.

6.	Give either 1, 2, or 4 points for positive reactions, 0 points for a negative reaction. Three test reactions are added together at a time to give your 7-digit API number which can be looked up in the codebook.

7.	You will be given an API 20E score sheet. Stick this into your laboratory notebook and use it to generate a profile number for the unknown culture. Look up the profile number in the API 20E index book to identify the organism. Record your results in Table 5.2.
