# Introduction: Identification of enterobacteria

There are many different techniques available to the clinical microbiologist who wishes to make a definitive identification of a potential pathogen. Many of these use the fact that different bacterial species have characteristic physiological and biochemical characteristics that can help to identify them.

In this laboratory session, you will be identifying pathogens of the intestinal tract (CASE STUDY 3) using differential and selective media (TASK 3A), and an API-20E set of biochemical tests (Task 3B). In CASE STUDY 4, you will be looking at some of the enzymes involved in aerobic metabolism using biochemical assays (TASK 3B), and at the ability of microbes to grow aerobically or anaerobically (TASK 3C).


 


Pathogenic enterobacteriaceae like Salmonella, Shigella, and E. coli are all relatively closely related, and they share a number of common characteristics – they are Gram-negative rods, non-spore-forming, facultative aerobes. However, they can be distinguished from one another by molecular methods or based on a number of biochemical tests, as can be seen in Table 5.
 
