project:
  type: book
  output-dir: _book

book:
  title: "BM327 Microbiology Semester 2 Lab Manual"
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  author: "Dr Morgan Feeney"
  date: "22/11/2024"
    
  # Define chapters and sections here
  # [E] CHAPTERS AND SECTIONS
  chapters:
    - index.qmd
    
    - part: 0section.qmd
      chapters:
        - text: "Aims"
          href: 0intro.qmd
        - text: "Competencies"
          href: 0competencies.qmd
        - text: "Schedule of Experimental Tasks"
          href: 0schedule.qmd
        - text: "Assessment"
          href: 0assessment.qmd  
        - text: "Lab Safety"
          href: 0safety.qmd
        - text: "Good Laboratory Technique"
          href: 0goodlab.qmd
        - text: "Aseptic Technique"
          href: 0aseptic.qmd
        - text: "Using a Microscope"
          href: 0microscope.qmd

    - part: 1section.qmd
      chapters: 
        - 1aims.qmd
        - 1intro1.qmd
        - 1intro2.qmd
        - 1intro3.qmd
        - 1protocols.qmd
        - 1data.qmd
        
    - part: 2section.qmd
      chapters: 
        - 2aims.qmd
        - 2intro.qmd
        - 2protocols.qmd
        - 2data.qmd
    
    - part: 3section.qmd
      chapters: 
        - 3aims.qmd
        - 3intro.qmd
        - 3protocols.qmd
        - 3data.qmd
        
    - part: 4section.qmd
      chapters: 
        - 4aims.qmd
        - 4intro.qmd
        - 4protocols.qmd
        - 4data.qmd
    
    - part: 5section.qmd
      chapters: 
        - 5aims.qmd
        - 5intro.qmd
        - 5protocols.qmd
        - 5data.qmd

  # Sidebar tools for quick navigation
  sidebar:
    tools:
      - icon: 0-square
        href: ./0section
      - icon: 1-square
        href: ./1section
      - icon: 2-square
        href: ./2section
      - icon: 3-square
        href: ./3section
      - icon: 4-square
        href: ./4section
      - icon: 5-square
        href: ./5section




# Additional settings
bibliography: references.bib



# Formatting and theme; may not need to be changed
format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "Leighton Pritchard"

# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto

# Add custom callouts
custom-callout:
  case-study:
    title: "Case Study"
    icon-symbol: "🔍"
    color: "#FFA500"
  data:
    icon-symbol: "📊"
    title: "Data Analysis"
    color: "#32CD32"
  discussion:
    title: "Discussion Questions:"
    icon-symbol: "✨"
    color: "#BA55D3"
  microbe:
    title: "Microbe Profile"
    icon-symbol: "🧫"
    color: "#1E90FF"
  thumbs-up:
    title: "Great job!"
    icon-symbol: "👍"
    color: "#008000"
  todo:
    icon-symbol: "📝"
    color: "pink"
    
    

filters:
  - custom-callout