project:
  type: book
  output-dir: _book

book:
  title: "BM327 Microbiology Semester 2 Lab Manual"
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  author: "Dr Morgan Feeney"
  date: "22/11/2024"
    
  # Define chapters and sections here
  # [E] CHAPTERS AND SECTIONS
  chapters:
    - index.qmd
    
    - part: section0.qmd
      chapters:
        - goodlab.qmd
        - aseptic.qmd
        - microscope.qmd

    - part: section1.qmd
      chapters: 
        - intro1.qmd
        - protocols1.qmd
        - data1.qmd
        
    - part: section2.qmd
      chapters: 
        - intro2.qmd
        - protocols2.qmd
        - data2.qmd
    
    - part: section3.qmd
      chapters: 
        - intro3.qmd
        - protocols3.qmd
        - data3.qmd
        
    - part: section4.qmd
      chapters: 
        - intro4.qmd
        - protocols4.qmd
        - data4.qmd
    
    - part: section5.qmd
      chapters: 
        - intro5.qmd
        - protocols5.qmd
        - data5.qmd

  # Sidebar tools for quick navigation
  sidebar:
    tools:
      - icon: 0-square
        href: ./section0
      - icon: 1-square
        href: ./section1
      - icon: 2-square
        href: ./section2
      - icon: 3-square
        href: ./section3
      - icon: 4-square
        href: ./section4
      - icon: 5-square
        href: ./section5




# Additional settings
bibliography: references.bib



# Formatting and theme; may not need to be changed
format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "Leighton Pritchard"
    
# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto
