# These variables define the project; they may not need to be changed
project:
  type: book
  output-dir: _book

# These variables define the book contents - adjust them as necessary
book:
  # [A] BOOK TITLE
  title: "BM327 Microbiology Semester 2 Lab Manual"
  
  # The cover image and favicon; these may not need to be changed
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  
  # Sets the page footer text/images
  # [B] FOOTER TEXT
  page-footer:
    left: |
      BM327 Microbiology S2 Lab Manual | Dr. Morgan Feeney
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  # Sets author information and publication/presentation date
  # [D] AUTHOR INFORMATION AND PUBLICATION/PRESENTATION DATE
  author: "Dr Morgan Feeney"
  date: "22/11/2024"

  # Define chapters and sections here
  # [E] CHAPTERS AND SECTIONS
  chapters:
    - index.qmd
    - intro.qmd

    - part: early-section.qmd
      chapters: 
        - early-section-topic.qmd
    
    - references.qmd

# Location of BibTeX format reference file; may not need to be changed
bibliography: references.bib

# Formatting and theme; may not need to be changed
format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "Leighton Pritchard"
    
    # Tools in the sidebar for quick navigation
    tools:
      - html: |
          <div style="display: flex; gap: 10px;">
            <a href="section0.qmd" title="Section 0">
              <i class="bi bi-0-square" style="font-size: 1.5rem;"></i>
            </a>
            <a href="section1.qmd" title="Section 1">
              <i class="bi bi-1-square" style="font-size: 1.5rem;"></i>
            </a>
            <a href="section2.qmd" title="Section 2">
              <i class="bi bi-2-square" style="font-size: 1.5rem;"></i>
            </a>
            <a href="section3.qmd" title="Section 3">
              <i class="bi bi-3-square" style="font-size: 1.5rem;"></i>
            </a>
            <a href="section4.qmd" title="Section 4">
              <i class="bi bi-4-square" style="font-size: 1.5rem;"></i>
            </a>
            <a href="section5.qmd" title="Section 5">
              <i class="bi bi-5-square" style="font-size: 1.5rem;"></i>
            </a>
          </div>

  pdf:
    documentclass: scrreprt

# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto
