project:
  type: book
  output-dir: _book

book:
  title: "BM327 Microbiology Semester 2 Lab Manual"
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  author: "Dr Morgan Feeney"
  date: "22/11/2024"
  
  chapters:
    - index.qmd

  # Sidebar tools for quick navigation
  sidebar:
    tools:
      - icon: 0-square
        href: ./section0
      - icon: 1-square
        href: ./section1
      - icon: 2-square
        href: ./section2
      - icon: 3-square
        href: ./section3
      - icon: 4-square
        href: ./section4
      - icon: 5-square
        href: ./section5




# Additional settings
bibliography: references.bib



# Formatting and theme; may not need to be changed
format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "Leighton Pritchard"
    
# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto
