# Preface {.unnumbered}

## Introduction to the BM327 Microbiology Semester 2 Lab Manual

This laboratory manual contains key information about each of the five practical laboratory sessions delivered as part of BM327 microbiology semester 2. 

### How to use this manual

You can navigate through this manual using the sidebar on the left

Each section 1-5 contains a brief explanation of the theory underpinning the practical lab session (section 0 is a general section containing helpful information on good laboratory technique, working with microorganisms safely and aseptically, etc.) Links to the handouts for each lab are provided, but please note that you do not need to print these out - they will be provided for you in the laboratories. 

You should read through the relevant theory/introductory material before coming to each practical lab session, and make sure you understand it. In some instances you may wish to 
If you notice any errors (including typos, broken links, etc.) please feel free to notify Dr Feeney by e-mail or by [raising an issue](https://github.com/mafeeney/BM327microS2/issues/new) on this lab manual's github page. 


## Background to Semester 2 Microbiology laboratory sessions

The aim of this laboratory is to introduce students to fundamental molecular biology and microbiology methods, such as Gram staining, the use of selective and differential media, identifying unknown microbes, and DNA analysis.

## Microbiology Laboratories Competency Skills

Graduate recruiters look for specific job skills and competencies. Competencies are action-oriented statements of the knowledge, skills, and abilities people need to do their work successfully. They are observable and measurable. These are what you need to do the job and work in their organisation. Some are straightforward and required in many different career: communication, teamwork and problem solving are just a few. You need to show employers you have mastered essential skills such as writing, reading, numeracy, presentation, organisation and the ability to work under pressure. Graduates who demonstrate their analytical thinking during a job interview or assessment centre will stand out from other candidates. Other skills such as those gained in the laboratory are more specific and aligned to particular types of jobs e.g. ability to do a PCR.

## Overall learning outcomes

- Students will understand how to examine microorganisms, both at the macroscopic (colony morphology), and the microscopic (including the use of appropriate staining techniques) scale.

- Students will understand how to identify unknown microorganisms using molecular and media-based techniques.

- Students will understand how to isolate and analyse plasmid DNA from microorganisms.

- Students will understand how to carry out PCR and interpret the results from multiplexed reactions.


## Assessment: Online Quiz

The formal assessment for the BM327semester 2 microbiology laboratory block will consist of a Myplace quiz taken outside of laboratory time.

This will be a mix of multiple choice and short answer questions testing your understanding of key knowledge learnt across all of the laboratories and workshop sessions.

Please refer to the BM327 microbiology class sub-page on Myplace for more information.

### Contribution to overall class assessment

The BM327 semester 2 microbiology assessment comprises 25% of the overall BM327 class assessment.




